use std::env;
use std::fs;
use std::path::Path;

/// Returns the user's home directory, defaulting to a specific path if HOME is not set.
fn get_home_dir() -> String {
    env::var("HOME").unwrap_or_else(|_| "/home/i4104".to_string())
}

/// Retrieves list of startup commands from Hyprland config.
#[tauri::command]
pub fn get_startup_commands() -> Vec<String> {
    let home = get_home_dir();
    let config_path = Path::new(&home).join(".config/hypr/exec.conf");
    let mut commands = Vec::new();

    if let Ok(content) = fs::read_to_string(config_path) {
        for line in content.lines() {
            let trim = line.trim();
            if trim.starts_with("exec-once") {
                if let Some((_, cmd)) = trim.split_once('=') {
                    commands.push(cmd.trim().to_string());
                }
            }
        }
    }
    commands
}

/// Saves startup commands to the Hyprland configuration file.
#[tauri::command]
pub fn save_startup_commands(commands: Vec<String>) -> Result<(), String> {
    let home = get_home_dir();
    let config_path = Path::new(&home).join(".config/hypr/exec.conf");

    // Ensure the config directory exists
    if let Some(parent) = config_path.parent() {
        let _ = fs::create_dir_all(parent);
    }

    let mut content = String::new();
    content.push_str("# Custom startup commands\n");
    content.push_str("# Auto-generated by Settings\n");

    for cmd in commands {
        if !cmd.trim().is_empty() {
            content.push_str(&format!("exec-once = {}\n", cmd.trim()));
        }
    }

    fs::write(config_path, content).map_err(|e| e.to_string())?;

    Ok(())
}
