use serde::{Deserialize, Serialize};
use std::env;
use std::fs;
use std::path::Path;

#[derive(Debug, Serialize, Deserialize)]
pub struct EnvVar {
    pub id: String,
    pub key: String,
    pub value: String,
}

fn get_home_dir() -> String {
    env::var("HOME").unwrap_or_else(|_| "/home/i4104".to_string())
}

#[tauri::command]
pub fn get_env_vars() -> Vec<EnvVar> {
    let home = get_home_dir();
    let config_path = Path::new(&home).join(".config/hypr/configs/env.conf");
    let mut vars = Vec::new();

    if let Ok(content) = fs::read_to_string(config_path) {
        for (index, line) in content.lines().enumerate() {
            let trim = line.trim();
            if trim.is_empty() || trim.starts_with('#') {
                continue;
            }

            // Expected format: env = KEY,VALUE
            if trim.starts_with("env =") {
                let parts: Vec<&str> = trim.trim_start_matches("env =").splitn(2, ',').collect();
                if parts.len() == 2 {
                    vars.push(EnvVar {
                        id: format!("env-{}", index),
                        key: parts[0].trim().to_string(),
                        value: parts[1].trim().to_string(),
                    });
                }
            }
        }
    }

    vars
}

#[tauri::command]
pub fn save_env_vars(vars: Vec<EnvVar>) -> Result<(), String> {
    let home = get_home_dir();
    let config_path = Path::new(&home).join(".config/hypr/configs/env.conf");

    // Create directory if it doesn't exist
    if let Some(parent) = config_path.parent() {
        let _ = fs::create_dir_all(parent);
    }

    let mut content = String::new();

    // Add header
    content.push_str("# Environment Variables Config\n");
    content.push_str("# Auto-generated by Settings\n\n");

    for var in vars {
        if !var.key.trim().is_empty() {
            content.push_str(&format!("env = {},{}\n", var.key.trim(), var.value.trim()));
        }
    }

    fs::write(config_path, content).map_err(|e| e.to_string())
}
